version: "3.8"

services:
  api:
    build: ./api
    container_name: api-service
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "5173:3000"
    depends_on:
      - api
